### ISSUE TITLE
5 Parcali Item

### ISSUE THREAD

**Issue by ffurkanhas** [ffurkanhas/dungeon#7]
Oyunda mevcut olan itemlerin dışında master bir item belirleyip o item'ı 5 parçaya bölerek her bir parçayı haritanın 5 farklı 	yerine random olarak yerleştiriceğim.Oyuncu her hangi bir parçasını bulduğunda diğer parçayı bulabilmesi için bir ipucu (bulmaca gibi koordinatlar hakkında ipucu,ipucu kullanıcının o anki harita konumuna göre belirlenecek) vericek.Oyuncu bu ipuçlarını kontrol ederek 5 parçayı tamamladığında master item'ı oluşturabilecek.Master item oyunda hasarı en fazla olan item 	olacak.(Bu düşen parçalar güçlü canavarları öldürünce düşecek.)

**Comment by cagdasgerede** [comment]
ok
