### ISSUE TITLE
Pet Sistemi

### ISSUE THREAD

**Issue by ffurkanhas** [ffurkanhas/dungeon#8]
Oyuna yeni ekleyeceğimiz bazı creatureları(kurt vs olabilir) kendi evcil hayvanımız yaparak onu savaşlara eklemeyi düşündüm. Dışarıdan bir eklenti gibi gözüksede oyun içinde pek çok dosyanın değişimine neden olacak.Bu hayvanları oyunda bulunan bazı yiyecekler ile evcilleştirebileceğiz ve bu besinler çantamızda yoksa bunu yapmak imkansız olacak. Ayrıca elimizde bu besinler olsa bile onu evcilleştirmek yinede kesin olmayacak ve bunu başaramazsak onunla savaşmak zorunda kalacağız. Evcilleştirdiğimiz hayvan sürekli yanımızda bulunacak ve daha önceden bellirttiğim gibi yaratıklar ile girdiğimiz mücadelelerde bize katkı sağlayacak.

**Comment by cagdasgerede** [comment]
ok
